###############################################
# TrustLab SSH Brute Force & APT Correlation System
# Configuration File
###############################################

# Kafka Configuration
kafka:
  broker: "<INSERT-HERE>"
  topics:
    - "web_auth" 
    - "webapt"
  consumer_group: "auth-consumer-group"

# File Paths
paths:
  # Log Files
  logs:
    base_dir: "${PROJECT_ROOT}/logs"
    raw_log: "${PROJECT_ROOT}/logs/kafka_logs_output.log"
    recent_log: "${PROJECT_ROOT}/logs/kafka_sixty.log"
    suspicious_log: "${PROJECT_ROOT}/logs/kafka_suspicious.log"
    apt_log: "${PROJECT_ROOT}/logs/apt_history_test.log"
    monitor_log: "${PROJECT_ROOT}/logs/apt_monitor.log"
  
  # Production Paths (for reference)
  production:
    apt_history: "/var/log/apt/history.log"
    kafka_log: "/home/primum/logs/kafka_sixty.log"
  
  # User Data
  user_data:
    userlist: "${PROJECT_ROOT}/config/userlist.json"
  
  # Model Files
  models:
    bruteforce_model: "${PROJECT_ROOT}/artifacts/bruteforce_model.pkl"

# Detection Configuration
detection:
  time_window_seconds: 60
  suspicious_keywords:
    - 'nmap'
    - 'masscan'
    - 'hydra'
    - 'john'
    - 'hashcat'
    - 'metasploit'
    - 'sqlmap'
    - 'nikto'
    - 'dirb'
    - 'gobuster'
    - 'burpsuite'
    - 'wireshark'
    - 'tcpdump'
    - 'netcat'
    - 'socat'
    - 'proxychains'
    - 'tor'
    - 'aircrack'
    - 'reaver'
    - 'ettercap'
    - 'beef'
    - 'armitage'
    - 'maltego'
    - 'backdoor'
    - 'rootkit'
    - 'keylogger'

# Monitoring Configuration
monitoring:
  check_interval: 60
  apt_time_window_hours: 24
